language: node_js
node_js:
  - "14"
cache:
  npm: false
branches:
  only:
    - main
    - feature/search-api
env:
  global:
    - PORT=3000
    - NODE_ENV=production
script:
  - npm run lint
  # - npm run test
install:
  - npm install
  - npm install -g eslint
# after_success: npm run coverage
