paths:
# [GET] clinic search
  /api/v1/clinic/search:
    get:
      tags:
      - clinic
      summary: Find clinic search results
      parameters:
      - name: clinicName
        in: query
        description: Name of clinic
        type: string
        required: false
      - name: state
        in: query
        description: Name of state
        type: string
        required: false
      - name: from
        in: query
        description: Available from time
        type: string
        required: false
      - name: to
        in: query
        description: Available to time
        type: string
        required: false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                anyOf:
                  - $ref: '#/components/schemas/DentalClinicSearchResponse'
                  - $ref: '#/components/schemas/VetsClinicSearchResponse'
        '500':
          description: 'Server Error'

# components
components:
  schemas:
    DentalClinicSearchResponse:
      type: object
      properties:
        status:
          type: string
        statusCode:
          type: string
        error:
          type: string
        payload:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                description: clinic name
              stateName:
                type: string
                description: name of state
              availability:
                type: object
                properties:
                  from:
                    type: string
                    description: Available from time
                  to:
                    type: string
                    description: Available to time
    VetsClinicSearchResponse:
      type: object
      properties:
        status:
          type: string
        statusCode:
          type: string
        error:
          type: string
        payload:
          type: array
          items:
            type: object
            properties:
              clinicName:
                type: string
                description: clinic name
              stateCode:
                type: string
                description: code of state
              opening:
                type: object
                properties:
                  from:
                    type: string
                    description: open from time
                  to:
                    type: string
                    description: open to time
